### ISSUE TITLE
Error on first launch

### ISSUE THREAD

**Issue by jessegavin** [threepointone/ratpack#2]
I downloaded the [release](https://github.com/threepointone/ratpack/releases/tag/0.1-prototype).

I moved the app into Applications folder.

I double clicked it and got the standard security warning that this app is not made from an identified developer.

I went to Settings > Security & Privacy to open the app anyways.

When the app started I got a dialog with the error below.  On my 2nd attempt to run the app, it worked fine.

--------

**A JavaScript error occurred in the main process**
```
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/Users/me/Library/Application Support/ratpack/extensions'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at getPath (/Applications/ratpack.app/Contents/Resources/app/node_modules/electron-devtools-installer/dist/utils.js:26:18)
    at Object.<anonymous> (/Applications/ratpack.app/Contents/Resources/app/node_modules/electron-devtools-installer/dist/index.js:42:59)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/ratpack.app/Contents/Resources/app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by OlegLustenko** [comment]
Do you have installed electron?

**Comment by kentcdodds** [comment]
Same issue here. I'm opening from the Desktop.

<img width="532" alt="screen shot 2017-01-04 at 10 16 07 am" src="https://cloud.githubusercontent.com/assets/1500684/21651708/e3450f9c-d266-11e6-9cef-c0c10950ef69.png">

<img width="698" alt="screen shot 2017-01-04 at 10 16 20 am" src="https://cloud.githubusercontent.com/assets/1500684/21651709/e357da32-d266-11e6-81ba-7afbb7de144e.png">

Works fine on the second open.

**Comment by threepointone** [comment]
Yeah this appears to be my bad, sorry! I have a fix, but I'm delaying until I get the autoupdating system in place. I'll leave this open till then.

**Comment by threepointone** [comment]
the build that's up doesn't have this issue anymore, closing this.
